sessions:
  cookieDomain: .secure-proxy.lan
  cookieName: SECURE_PROXY_SESSION
  ttlSeconds: 180
users:
  - username: user1
    totpSecret: FC5PJKPSPKIO5HE2Y5YDIEJJ3ZOJ5J3K
    availableDomains:
      - site1.secure-proxy.lan
upstreams:
  - host: site1.secure-proxy.lan # должен быть поддоменом .secure-proxy.lan, чтобы мы могли увидеть куку
    destination: http://127.0.0.1:8081 # куда проксировать успешно аутентифицированные запросы